//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.23 at 02:19:17 AM EET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "libraryService", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ua.com.epam.entities;
